### ISSUE TITLE
Update dependent libraries

### ISSUE THREAD

**Issue by ktanaka101** [ktanaka101/nail#852]
Tasks:
- [x] Update all dependencies #883 
- [ ] Update salsa to the latest version #885
- [x] Update inkwell to the latest version #884
